### PR TITLE
Use keepalive

### PR DESCRIPTION
**Pull request by ryansch**

### CODE REVIEW

**Review by morganick — APPROVED** [review]

**Comment by morganick** [comment]
@ryansch does this still need to be merged?

**Comment by ryansch** [comment]
Whoa check out that stale code.

**Comment by ryansch** [comment]
Probably, but I'm going to need to remember what's going on here.

**Comment by ryansch** [comment]
Nevermind, this is what we've been running in production for over a year.

**Comment by morganick** [comment]
🎉

**Pull request merged**
